= About

Scientific Nutrition and Dietary Intake Assessment

Dita is a research initiative that focuses on creating specifications and data transfer objects. 
These can be utilized for collecting, storing, and analyzing dietary intake data. 
Additionally, the project provides building blocks to assist application developers 
in creating customized solutions for dietary data collection and analysis.

Dita Source Code Repository: https://github.com/univie-nutrition/dita[GitHub]

== Design Documents

* xref:designdocs/FoodModelMapping.adoc[Food Model Mapping]
* xref:designdocs/InterviewModel.adoc[Interview Model]
* xref:designdocs/CampaignManager.adoc[Campaign Manager]
* xref:designdocs/ConsumptionReporting.adoc[Consumption Reporting]
* xref:designdocs/NutrientMapping.adoc[Nutrient Mapping]
* xref:designdocs/OntologyTermAndAnnotations.adoc[Ontology Term And Annotations (Draft)]

== Schema URLs

* Recall-24: https://univie-nutrition.github.io/dita/schema/dita-recall24.xsd

== License
Dita is _Open Source_ software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
