/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 */
// Auto-generated by DitA-Tooling
package dita.globodiet.dom.params.food_list;

import dita.globodiet.dom.params.classification.FoodGroup;
import jakarta.inject.Inject;
import java.util.Objects;
import lombok.RequiredArgsConstructor;
import org.apache.causeway.applib.annotation.MemberSupport;
import org.apache.causeway.applib.annotation.Property;
import org.apache.causeway.applib.annotation.PropertyLayout;
import org.apache.causeway.applib.services.repository.RepositoryService;

@Property(
        snapshot = org.apache.causeway.applib.annotation.Snapshot.EXCLUDED
)
@PropertyLayout(
        sequence = "2.1",
        describedAs = "Food Group code"
)
@RequiredArgsConstructor
public class FoodOrProductOrAlias_foodGroupCode {
    @Inject
    RepositoryService repositoryService;

    private final FoodOrProductOrAlias mixee;

    @MemberSupport
    public FoodGroup prop() {
        return repositoryService
            .uniqueMatch(FoodGroup.class,
                foreign->Objects.equals(foreign.getFoodGroupCode(), mixee.getFoodGroupCode()))
            .orElse(null);
    }
}
