/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Auto-generated by DitA-Tooling
package dita.globodiet.dom.params.recipe_list;

import dita.commons.services.search.SearchService;
import jakarta.inject.Named;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.DatastoreIdentity;
import javax.jdo.annotations.Extension;
import javax.jdo.annotations.PersistenceCapable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.apache.causeway.applib.ViewModel;
import org.apache.causeway.applib.annotation.Collection;
import org.apache.causeway.applib.annotation.DomainObject;
import org.apache.causeway.applib.annotation.DomainObjectLayout;
import org.apache.causeway.applib.annotation.Editing;
import org.apache.causeway.applib.annotation.ObjectSupport;
import org.apache.causeway.applib.annotation.Optionality;
import org.apache.causeway.applib.annotation.Property;
import org.apache.causeway.applib.annotation.PropertyLayout;
import org.apache.causeway.applib.annotation.Where;

/**
 * Mixed recipes: Ingredients description/quantification
 */
@Named("dita.globodiet.params.recipe_list.RecipeIngredient")
@DomainObject
@DomainObjectLayout(
        describedAs = "Mixed recipes: Ingredients description/quantification"
)
@PersistenceCapable(
        table = "MIXEDING"
)
@DatastoreIdentity(
        strategy = javax.jdo.annotations.IdGeneratorStrategy.IDENTITY,
        column = "id"
)
public class RecipeIngredient {
    /**
     * Recipe ID number the ingredient belongs to
     */
    @Property
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "1",
            describedAs = "Recipe ID number the ingredient belongs to",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "R_IDNUM",
            allowsNull = "false",
            length = 5
    )
    @Getter
    @Setter
    private String recipeCode;

    /**
     * 1 = ingredient fixed
     * 2 = ingredient substitutable
     * 3 = fat during cooking
     * A2 = type of fat used
     * A3 = type of milk/liquid used
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "2",
            describedAs = "1 = ingredient fixed\n"
                            + "2 = ingredient substitutable\n"
                            + "3 = fat during cooking\n"
                            + "A2 = type of fat used\n"
                            + "A3 = type of milk/liquid used",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "ING_TYPE",
            allowsNull = "false",
            length = 2
    )
    @Getter
    @Setter
    @Extension(
            vendorName = "datanucleus",
            key = "enum-check-constraint",
            value = "true"
    )
    @Extension(
            vendorName = "datanucleus",
            key = "enum-value-getter",
            value = "getMatchOn"
    )
    private Substitutable substitutable;

    /**
     * Food type (GI or blank)
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "3",
            describedAs = "Food type (GI or blank)",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "TYPE",
            allowsNull = "true",
            length = 2
    )
    @Getter
    @Setter
    private String foodType;

    /**
     * Description text (facet/descriptor text)
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "4",
            describedAs = "Description text (facet/descriptor text)",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "TEXT",
            allowsNull = "true",
            length = 4096
    )
    @Getter
    @Setter
    private String descriptionText;

    /**
     * Ingredient name
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "5",
            describedAs = "Ingredient name",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "NAME",
            allowsNull = "false",
            length = 100
    )
    @Getter
    @Setter
    private String name;

    /**
     * Ingredient food or recipe group
     */
    @Property
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "6",
            describedAs = "Ingredient food or recipe group",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "GROUP",
            allowsNull = "false",
            length = 2
    )
    @Getter
    @Setter
    private String foodOrRecipeGroupCode;

    /**
     * Ingredient food or recipe subgroup
     */
    @Property
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "7",
            describedAs = "Ingredient food or recipe subgroup",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "SUBGROUP1",
            allowsNull = "false",
            length = 2
    )
    @Getter
    @Setter
    private String foodOrRecipeSubgroupCode;

    /**
     * Ingredient food sub-subgroup
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "8",
            describedAs = "Ingredient food sub-subgroup",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "SUBGROUP2",
            allowsNull = "true",
            length = 2
    )
    @Getter
    @Setter
    private String foodSubSubgroupCode;

    /**
     * Ingredient brand (if any)
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "9",
            describedAs = "Ingredient brand (if any)",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "BRANDNAME",
            allowsNull = "true",
            length = 100
    )
    @Getter
    @Setter
    private String brandName;

    /**
     * Facets-Descriptors codes used to describe the ingredient;
     * multiple (descface.facet_code + descface.descr_code) comma separated (e.g. 0401,0203,051)
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "10",
            describedAs = "Facets-Descriptors codes used to describe the ingredient;\n"
                            + "multiple (descface.facet_code + descface.descr_code) comma separated (e.g. 0401,0203,051)",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FACETS_STR",
            allowsNull = "true",
            length = 4096
    )
    @Getter
    @Setter
    private String facetDescriptorsLookupKey;

    /**
     * 1 = ingredient described and quantified
     * 2 = otherwise
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "11",
            describedAs = "1 = ingredient described and quantified\n"
                            + "2 = otherwise",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "STATUS",
            allowsNull = "false",
            length = 1
    )
    @Getter
    @Setter
    @Extension(
            vendorName = "datanucleus",
            key = "enum-check-constraint",
            value = "true"
    )
    @Extension(
            vendorName = "datanucleus",
            key = "enum-value-getter",
            value = "getMatchOn"
    )
    private DescribedAndQuantifiedQ describedAndQuantifiedQ;

    /**
     * Final quantity in g (with coefficient applied)
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "12",
            describedAs = "Final quantity in g (with coefficient applied)",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "CONS_QTY",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double finalQuantityInG;

    /**
     * Estimated quantity (before coefficient applied)
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "13",
            describedAs = "Estimated quantity (before coefficient applied)",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "ESTIM_QTY",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double estimatedQuantityBeforeCoefficientApplied;

    /**
     * Quantity Estimated Raw or Cooked
     * 1 = Raw
     * 2 = Cooked or Not applicable
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "14",
            describedAs = "Quantity Estimated Raw or Cooked\n"
                            + "1 = Raw\n"
                            + "2 = Cooked or Not applicable",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "RAWCOOKED",
            allowsNull = "false",
            length = 1
    )
    @Getter
    @Setter
    @Extension(
            vendorName = "datanucleus",
            key = "enum-check-constraint",
            value = "true"
    )
    @Extension(
            vendorName = "datanucleus",
            key = "enum-value-getter",
            value = "getMatchOn"
    )
    private QuantityEstimatedRawOrCooked quantityEstimatedRawOrCooked;

    /**
     * Quantity Consumed Raw or Cooked
     * 1 = Raw
     * 2 = Cooked or Not applicable
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "15",
            describedAs = "Quantity Consumed Raw or Cooked\n"
                            + "1 = Raw\n"
                            + "2 = Cooked or Not applicable",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "CONSRAWCO",
            allowsNull = "false",
            length = 1
    )
    @Getter
    @Setter
    @Extension(
            vendorName = "datanucleus",
            key = "enum-check-constraint",
            value = "true"
    )
    @Extension(
            vendorName = "datanucleus",
            key = "enum-value-getter",
            value = "getMatchOn"
    )
    private QuantityConsumedRawOrCooked quantityConsumedRawOrCooked;

    /**
     * Conversion factor raw->cooked
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "16",
            describedAs = "Conversion factor raw->cooked",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "CONVER",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double conversionFactorRawToCooked;

    /**
     * Quantity as estimated: 1=without un-edible part & 2=with un-edible part
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "17",
            describedAs = "Quantity as estimated: 1=without un-edible part & 2=with un-edible part",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "EDIB",
            allowsNull = "false",
            length = 1
    )
    @Getter
    @Setter
    @Extension(
            vendorName = "datanucleus",
            key = "enum-check-constraint",
            value = "true"
    )
    @Extension(
            vendorName = "datanucleus",
            key = "enum-value-getter",
            value = "getMatchOn"
    )
    private WithUnediblePartQ withUnediblePartQ;

    /**
     * Conversion factor for edible part
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "18",
            describedAs = "Conversion factor for edible part",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "EDIB_CSTE",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double conversionFactorForEdiblePart;

    /**
     * Quantity in gram/volume attached to the selected Photo, HHM, STDU
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "19",
            describedAs = "Quantity in gram/volume attached to the selected Photo, HHM, STDU",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "NGRAMS",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double quantityInGramPerVolumeAttachedToTheSelectedPhotoOrHHMOrSTDU;

    /**
     * Proportion of Photo, HHM, STDU
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "20",
            describedAs = "Proportion of Photo, HHM, STDU",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "PROPORT",
            allowsNull = "false",
            length = 5
    )
    @Getter
    @Setter
    private String proportionOfPhotoHHMSTDU;

    /**
     * Type of quantification method
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "21",
            describedAs = "Type of quantification method",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "Q_METHOD",
            allowsNull = "true",
            length = 1
    )
    @Getter
    @Setter
    private String typeOfQuantificationMethod;

    /**
     * Quantification method code
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "22",
            describedAs = "Quantification method code",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "QM_CODE",
            allowsNull = "true",
            length = 4
    )
    @Getter
    @Setter
    private String quantificationMethodCode;

    /**
     * Density Coefficient only for HHM
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "23",
            describedAs = "Density Coefficient only for HHM",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "DENSITY",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double densityCoefficientOnlyForHHM;

    /**
     * Sequential Number for Ingredients within a Mixed Recipe
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "24",
            describedAs = "Sequential Number for Ingredients within a Mixed Recipe",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "ING_NUM",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double sequentialNumberForIngredientsWithinARecipe;

    /**
     * Fat Left-Over Percentage
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "25",
            describedAs = "Fat Left-Over Percentage",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "FATL_PCT",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double fatLeftOverPercentage;

    /**
     * Fat Left-Over Code (F=False, T=True)
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "26",
            describedAs = "Fat Left-Over Code (F=False, T=True)",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "FATLEFTO",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private boolean fatLeftOverQ;

    /**
     * HHM Fraction
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "27",
            describedAs = "HHM Fraction",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "HHMFRACT",
            allowsNull = "true",
            length = 5
    )
    @Getter
    @Setter
    private String hhmFraction;

    /**
     * Consumed quantity in pound
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "28",
            describedAs = "Consumed quantity in pound",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "POUND",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double consumedQuantityInPound;

    /**
     * Consumed quantity in ounce
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "29",
            describedAs = "Consumed quantity in ounce",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "OUNCE",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double consumedQuantityInOunce;

    /**
     * Consumed quantity in quart
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "30",
            describedAs = "Consumed quantity in quart",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "QUART",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double consumedQuantityInQuart;

    /**
     * Consumed quantity in pint
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "31",
            describedAs = "Consumed quantity in pint",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "PINT",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double consumedQuantityInPint;

    /**
     * Consumed quantity in flounce
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "32",
            describedAs = "Consumed quantity in flounce",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "FLOUNCE",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double consumedQuantityInFlounce;

    /**
     * Sequential Number for Ingredients within a Sub-Recipe
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "33",
            describedAs = "Sequential Number for Ingredients within a Sub-Recipe",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "S_ING_NUM",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double sequentialNumberForIngredientsWithinASubRecipe;

    /**
     * Raw quantity without inedible (sans dechet)
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "34",
            describedAs = "Raw quantity without inedible (sans dechet)",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "RAW_Q",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double rawQuantityWithoutInedible;

    /**
     * Percentage/Proportion as Estimated for Recipe Ingredients
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "35",
            describedAs = "Percentage/Proportion as Estimated for Recipe Ingredients",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "PCT_ESTIM",
            allowsNull = "true"
    )
    @Getter
    @Setter
    private Double percentageOrProportionAsEstimatedForRecipeIngredients;

    /**
     * Percentage/Proportion as Consumed for Recipe Ingredients
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "36",
            describedAs = "Percentage/Proportion as Consumed for Recipe Ingredients",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "PCT_CONS",
            allowsNull = "true"
    )
    @Getter
    @Setter
    private Double percentageOrProportionAsConsumedForRecipeIngredients;

    /**
     * 1 = food
     * 2 = recipe
     */
    @Property(
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "37",
            describedAs = "1 = food\n"
                            + "2 = recipe",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "TYPE_IT",
            allowsNull = "false"
    )
    @Getter
    @Setter
    @Extension(
            vendorName = "datanucleus",
            key = "enum-check-constraint",
            value = "true"
    )
    @Extension(
            vendorName = "datanucleus",
            key = "enum-value-getter",
            value = "getMatchOn"
    )
    private TypeOfItem typeOfItem;

    /**
     * Ingredient Food or Recipe ID number; either Foods.foodnum OR Mixedrec.r_idnum
     */
    @Property
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "38",
            describedAs = "Ingredient Food or Recipe ID number; either Foods.foodnum OR Mixedrec.r_idnum",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "IDNUM",
            allowsNull = "false",
            length = 5
    )
    @Getter
    @Setter
    private String foodOrRecipeCode;

    /**
     * Unit of selected quantity for method Photo, std U, std P (G=gram, V=volum)
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "39",
            describedAs = "Unit of selected quantity for method Photo, std U, std P (G=gram, V=volum)",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "Q_UNIT",
            allowsNull = "true",
            length = 1
    )
    @Getter
    @Setter
    private String unitOfSelectedQuantityForMethod;

    /**
     * has no description
     */
    @Property(
            optionality = Optionality.OPTIONAL,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "40",
            describedAs = "has no description",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "PCT_RAW",
            allowsNull = "true"
    )
    @Getter
    @Setter
    private Double percentageRaw;

    @ObjectSupport
    public String title() {
        return this.toString();
    }

    @RequiredArgsConstructor
    public enum Substitutable {
        /**
         * no description
         */
        INGREDIENT_FIXED("1", "ingredient fixed"),

        /**
         * no description
         */
        INGREDIENT_SUBSTITUTABLE("2", "ingredient substitutable"),

        /**
         * no description
         */
        FAT_DURING_COOKING("3", "fat during cooking"),

        /**
         * no description
         */
        TYPE_OF_FAT_USED("A2", "type of fat used"),

        /**
         * no description
         */
        TYPE_OF_MILK_LIQUID_USED("A3", "type of milk/liquid used");

        @Getter
        private final String matchOn;

        @Getter
        @Accessors(
                fluent = true
        )
        private final String title;
    }

    @RequiredArgsConstructor
    public enum DescribedAndQuantifiedQ {
        /**
         * no description
         */
        INGREDIENT_DESCRIBED_AND_QUANTIFIED("1", "ingredient described and quantified"),

        /**
         * no description
         */
        OTHERWISE("2", "otherwise");

        @Getter
        private final String matchOn;

        @Getter
        @Accessors(
                fluent = true
        )
        private final String title;
    }

    @RequiredArgsConstructor
    public enum QuantityEstimatedRawOrCooked {
        /**
         * no description
         */
        RAW("1", "Raw"),

        /**
         * no description
         */
        COOKED_OR_NOT_APPLICABLE("2", "Cooked or Not applicable");

        @Getter
        private final String matchOn;

        @Getter
        @Accessors(
                fluent = true
        )
        private final String title;
    }

    @RequiredArgsConstructor
    public enum QuantityConsumedRawOrCooked {
        /**
         * no description
         */
        RAW("1", "Raw"),

        /**
         * no description
         */
        COOKED_OR_NOT_APPLICABLE("2", "Cooked or Not applicable");

        @Getter
        private final String matchOn;

        @Getter
        @Accessors(
                fluent = true
        )
        private final String title;
    }

    @RequiredArgsConstructor
    public enum WithUnediblePartQ {
        /**
         * no description
         */
        UN_EDIBLE_EXCLUDED("1", "un-edible excluded"),

        /**
         * no description
         */
        UN_EDIBLE_INCLUDED("2", "un-edible included");

        @Getter
        private final String matchOn;

        @Getter
        @Accessors(
                fluent = true
        )
        private final String title;
    }

    @RequiredArgsConstructor
    public enum TypeOfItem {
        /**
         * no description
         */
        FOOD(1, "Food"),

        /**
         * no description
         */
        RECIPE(2, "Recipe");

        @Getter
        private final int matchOn;

        @Getter
        @Accessors(
                fluent = true
        )
        private final String title;
    }

    /**
     * Manager Viewmodel for @{link RecipeIngredient}
     */
    @Named("dita.globodiet.params.recipe_list.RecipeIngredient.Manager")
    @DomainObjectLayout(
            describedAs = "Mixed recipes: Ingredients description/quantification"
    )
    @AllArgsConstructor
    public static final class Manager implements ViewModel {
        public final SearchService searchService;

        @Property(
                optionality = Optionality.OPTIONAL,
                editing = Editing.ENABLED
        )
        @PropertyLayout(
                fieldSetId = "searchBar"
        )
        @Getter
        @Setter
        private String search;

        @ObjectSupport
        public String title() {
            return "Manage Recipe Ingredient";
        }

        @Collection
        public final List<RecipeIngredient> getListOfRecipeIngredient() {
            return searchService.search(RecipeIngredient.class, RecipeIngredient::title, search);
        }

        @Override
        public final String viewModelMemento() {
            return getSearch();
        }
    }
}
