#
# Recommend use for static configuration that does not change between environments.
#
# See also config/application.properties
#
causeway:

  applib:
    annotation:
      action:
        explicit: true
        command-publishing: all
        execution-publishing: all
      action-layout:
        css-class:
          patterns:
            add.*:btn-primary,
            clone.*:btn-warning,
            delete.*:btn-danger,
            remove.*:btn-warning,
            new.*:btn-primary,
            create.*:btn-primary,
            delete.*:btn-danger,
            verify.*:btn-success,
            save.*:btn-success
      property:
        command-publishing: all
        execution-publishing: all
      domain-object:
        editing: false
        entity-change-publishing: all
  core:
    meta-model:
      introspector:
        lock-after-full-introspection: true
        policy: ANNOTATION_REQUIRED
      validator:
        allow-deprecated: false
        no-params-only: true
        explicit-object-type: true

    runtime-services:
      translation:
        po:
          mode: disabled

  extensions:
    secman:
      seed:
        # yaml-file: configured in custom config
        admin:
          user-name: "secman-admin"
          password: "pass"
          role-name: "causeway-ext-secman-admin"
          namespace-permissions:
            sticky: "dita"
#            additional: ...
        regular-user:
          role-name: "causeway-ext-secman-user"
      permissions-evaluation-policy: allow_beats_veto
      user-menu-me-action-policy: hide

  viewer:
    common:
      application:
        about: Dita Globodiet Manager
        brand-logo-signin: images/dita/dita-logo-banner.png
        brand-logo-header: images/dita/dita-logo-48px.png
        favicon-url: images/favicon.png
        menubars-layout-file: menubars.layout.xml
        name: Dita Globodiet Manager
        version: 1.0.0-SNAPSHOT
      credit:
        - url:  https://nutrition.univie.ac.at/
          image: images/credit/uni-logo.jpg
          name: University of Vienna (Nutrition)
        - url:  https://github.com/univie-nutrition/dita
          image: images/credit/github-mark.svg
          name: Dita Project (Github)
    restfulobjects:
      basePath: /restful
    wicket:
      basePath: /w/
      css: css/application.css
      js: scripts/application.js

      bookmarked-pages:
        show-chooser: false
        show-drop-down-on-footer: false

      dialog-mode: modal
      dialog-mode-for-menu: modal
      
      disableReasonExplanationInPrototypingModeEnabled: false

      max-title-length-in-standalone-tables: 0
      max-title-length-in-parented-tables: 0

      themes:
        initial: Default
        show-chooser: false
        
      tooltip-text-mode: html

      table:
        decoration:
          data-tables-net:
            options: "info: false, pagingType: 'numbers'"

server:
  max-http-header-size: 16KB

spring:
  banner:
    location: banner.txt
