/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */
// Auto-generated by DitA-Tooling
package dita.globodiet.manager;

import jakarta.inject.Inject;
import jakarta.inject.Named;

import org.apache.causeway.applib.annotation.Action;
import org.apache.causeway.applib.annotation.ActionLayout;
import org.apache.causeway.applib.annotation.DomainService;
import org.apache.causeway.applib.services.factory.FactoryService;

import dita.commons.services.search.SearchService;
import dita.globodiet.dom.params.food_descript.Brand;
import dita.globodiet.dom.params.food_descript.Brand.Manager;
import dita.globodiet.dom.params.food_list.Food;

@Named(DitaModuleGdManager.NAMESPACE + ".FeaturedMenu")
@DomainService(
        nature = org.apache.causeway.applib.annotation.NatureOfService.VIEW
        )
public class FeaturedMenu {

    @Inject FactoryService factoryService;
    @Inject SearchService searchService;

    //TODO autogen?

    @Action
    @ActionLayout(cssClassFa = FontawesomeConstants.ICON_BRANDS)
    public Manager manageBrand() {
        return factoryService.viewModel(new Brand.Manager(searchService, ""));
    }

    @Action
    @ActionLayout(cssClassFa = FontawesomeConstants.ICON_FOOD)
    public Food.Manager manageFood() {
        return factoryService.viewModel(new Food.Manager(searchService, ""));
    }

}
