site:
  title: Dita Docs
  url: https://univie-nutrition.github.io/dita
  start_page: component-main::index.adoc
content:
  sources:
  - url: /antora
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.12/ui-bundle.zip
    snapshot: true