site:
  title: Dita Docs
  url: https://univie-nutrition.github.io/dita
  start_page: component-main::about.adoc
content:
  sources:
  - url: https://github.com/univie-nutrition/dita.git
    branches: HEAD
    start_path: antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true