= Dita

Scientific Nutrition and Dietary Intake Assessment (Umbrella Project, started in 2023)

Dita is a research initiative that aims at development of specifications 
and data transfer objects that can be used to collect, store and analyze dietary intake data. 

In particular, the project aims to provide various building blocks
for application developers to make tools that manage configuration and allow access to the collected data.

Rough overview of aspects of interest (work in progress): 

* Food Description Models (such as FoodEx/EFSA and Globodiet; using _Facet Catalogs_)
* Configuration Data Model for an interview application (such as Globodiet)
* Interview Data Specification (XML) with accompanied Data Transfer Objects (DTOs)
* Data Validation (Rule Checkers)
* File Formats and Interfaces for Data Exchange (XML, YAML, JSON, EXCEL, etc.)

== Technology Stack

* Java (17+) - Programming Language
* Spring Boot - Orchestration
* Apache Causeway - Application Framework

== Modules

* xref:foodex/validator/README.adoc[Foodex Validator]
* xref:globodiet/README.adoc[Globodiet]
* to be continued ..

== License
Dita is _Open Source_ software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
  