= Dita

Scientific Nutrition and Dietary Intake Assessment (Umbrella Project, started in 2023)

Dita is a research initiative that aims at development of specifications 
and data transfer objects that can be used to collect, store and analyze dietary intake data. 

In particular, the project aims to provide various building blocks
for application developers to make tools that manage configuration and allow access to the collected data.

Rough overview of aspects of interest (work in progress): 

* Food Description Models (such as FoodOn, LanguaL, FoodEx(EFSA) and GloboDiet)
* Configuration Data Model for an interview application (such as GloboDiet)
* Specification of Recall-24 Interview Data (XML) with accompanied Data Transfer Objects (DTOs)
* Data Validation (Rule Checkers)
* File Formats and Interfaces for Data Exchange (XML, YAML, JSON, EXCEL, etc.)

For more details see https://univie-nutrition.github.io/dita[Dita Documentation]

== Technology Stack

* Java (21+) - Programming Language
* Spring Boot - Orchestration
* Apache Causeway - Application Framework

== License
Dita is _Open Source_ software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
  