= Dita

Scientific Nutrition and Dietary Intake Assessment

Dita is a research initiative that focuses on creating specifications and data transfer objects. 
These can be utilized for collecting, storing, and analyzing dietary intake data. 
Additionally, the project provides building blocks to assist application developers 
in creating customized solutions for dietary data collection and analysis.

The project started in 2023.

Aspects of interest: 

* Integration of _Food Description Models_ such as FoodOn, LanguaL, FoodEx (EFSA) or GloboDiet
* _Configuration Data Management_ for an interview application (such as GloboDiet)
* Specification of _Recall-24_ Interview Data (XML) and accompanied _Data Transfer Objects_ (DTOs)
* Data Validation (Rule Checkers)
* File Formats and Interfaces for Data Exchange (XML, YAML, JSON, EXCEL, etc.)

For more details see https://univie-nutrition.github.io/dita[Dita Documentation]

== Technology Stack

* Java - Programming Language
* Spring Framework - Orchestration - https://spring.io/projects/spring-framework
* Apache Causeway - Application Framework - https://causeway.apache.org/

== License
Dita is _Open Source_ software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
  