/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Auto-generated by Causeway-Stuff code generator.
package dita.globodiet.params.food_coefficient;

import io.github.causewaystuff.companion.applib.services.lookup.Cloneable;
import io.github.causewaystuff.companion.applib.services.search.SearchService;
import jakarta.inject.Inject;
import jakarta.inject.Named;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import javax.annotation.processing.Generated;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.DatastoreIdentity;
import javax.jdo.annotations.NotPersistent;
import javax.jdo.annotations.PersistenceCapable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.apache.causeway.applib.ViewModel;
import org.apache.causeway.applib.annotation.Collection;
import org.apache.causeway.applib.annotation.DomainObject;
import org.apache.causeway.applib.annotation.DomainObjectLayout;
import org.apache.causeway.applib.annotation.Editing;
import org.apache.causeway.applib.annotation.Nature;
import org.apache.causeway.applib.annotation.Navigable;
import org.apache.causeway.applib.annotation.ObjectSupport;
import org.apache.causeway.applib.annotation.Optionality;
import org.apache.causeway.applib.annotation.Programmatic;
import org.apache.causeway.applib.annotation.Property;
import org.apache.causeway.applib.annotation.PropertyLayout;
import org.apache.causeway.applib.annotation.Snapshot;
import org.apache.causeway.applib.annotation.Where;
import org.apache.causeway.applib.services.repository.RepositoryService;

/**
 * % of fat use during cooking attached to a food
 */
@Generated("io.github.causewaystuff.companion.codegen.domgen._GenEntity")
@Named("dita.globodiet.params.food_coefficient.PercentOfFatUseDuringCookingForFood")
@DomainObject
@DomainObjectLayout(
        describedAs = "% of fat use during cooking attached to a food",
        cssClassFa = "solid percent"
)
@PersistenceCapable(
        table = "SPFDCOOK"
)
@DatastoreIdentity(
        strategy = javax.jdo.annotations.IdGeneratorStrategy.IDENTITY,
        column = "id"
)
public class PercentOfFatUseDuringCookingForFood implements Cloneable<PercentOfFatUseDuringCookingForFood> {
    @Inject
    RepositoryService repositoryService;

    @Inject
    SearchService searchService;

    /**
     * Food group code
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "1",
            describedAs = "Food group code",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FOOD_GROUP",
            allowsNull = "true",
            length = 2
    )
    @Getter
    @Setter
    private String foodGroupCode;

    /**
     * Food subgroup code
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "2",
            describedAs = "Food subgroup code",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FOOD_SUBG1",
            allowsNull = "true",
            length = 2
    )
    @Getter
    @Setter
    private String foodSubgroupCode;

    /**
     * Food sub-Subgroup code
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "3",
            describedAs = "Food sub-Subgroup code",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FOOD_SUBG2",
            allowsNull = "true",
            length = 2
    )
    @Getter
    @Setter
    private String foodSubSubgroupCode;

    /**
     * Food code
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "4",
            describedAs = "Food code",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FOOD_IDNUM",
            allowsNull = "true",
            length = 5
    )
    @Getter
    @Setter
    private String foodCode;

    /**
     * Group code for fat (not used)
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "5",
            describedAs = "Group code for fat (not used)",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FAT_GROUP",
            allowsNull = "true",
            length = 2
    )
    @Getter
    @Setter
    private String fatGroupCode;

    /**
     * Subgroup code for fat (not used)
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "6",
            describedAs = "Subgroup code for fat (not used)",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FAT_SUBG1",
            allowsNull = "true",
            length = 2
    )
    @Getter
    @Setter
    private String fatSubgroupCode;

    /**
     * Sub-subgroup code for fat (not used)
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "7",
            describedAs = "Sub-subgroup code for fat (not used)",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FAT_SUBG2",
            allowsNull = "true",
            length = 2
    )
    @Getter
    @Setter
    private String fatSubSubgroupCode;

    /**
     * Code for fat (not used)
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "8",
            describedAs = "Code for fat (not used)",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "FAT_IDNUM",
            allowsNull = "true",
            length = 5
    )
    @Getter
    @Setter
    private String fatCode;

    /**
     * Cooking method Facet and Descriptor codes (e.g. 0305)
     */
    @Property(
            optionality = Optionality.MANDATORY
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "9",
            describedAs = "Cooking method Facet and Descriptor codes (e.g. 0305)",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "COOK_METH",
            allowsNull = "false",
            length = 4
    )
    @Getter
    @Setter
    private String cookingMethodFacetDescriptorLookupKey;

    /**
     * Percentage of fat absorbed during cooking
     */
    @Property(
            optionality = Optionality.MANDATORY,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "10",
            describedAs = "Percentage of fat absorbed during cooking"
    )
    @Column(
            name = "PCT_ABSOR",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double percentageOfFatAbsorbedDuringCooking;

    @ObjectSupport
    public String title() {
        return this.toString();
    }

    @Override
    public String toString() {
        return "PercentOfFatUseDuringCookingForFood(" + "foodGroupCode=" + getFoodGroupCode() + ","
         +"foodSubgroupCode=" + getFoodSubgroupCode() + ","
         +"foodSubSubgroupCode=" + getFoodSubSubgroupCode() + ","
         +"foodCode=" + getFoodCode() + ","
         +"fatGroupCode=" + getFatGroupCode() + ","
         +"fatSubgroupCode=" + getFatSubgroupCode() + ","
         +"fatSubSubgroupCode=" + getFatSubSubgroupCode() + ","
         +"fatCode=" + getFatCode() + ","
         +"cookingMethodFacetDescriptorLookupKey=" + getCookingMethodFacetDescriptorLookupKey() + ","
         +"percentageOfFatAbsorbedDuringCooking=" + getPercentageOfFatAbsorbedDuringCooking() + ")";
    }

    @Programmatic
    @Override
    public PercentOfFatUseDuringCookingForFood copy() {
        var copy = repositoryService.detachedEntity(new PercentOfFatUseDuringCookingForFood());
        copy.setFoodGroupCode(getFoodGroupCode());
        copy.setFoodSubgroupCode(getFoodSubgroupCode());
        copy.setFoodSubSubgroupCode(getFoodSubSubgroupCode());
        copy.setFoodCode(getFoodCode());
        copy.setFatGroupCode(getFatGroupCode());
        copy.setFatSubgroupCode(getFatSubgroupCode());
        copy.setFatSubSubgroupCode(getFatSubSubgroupCode());
        copy.setFatCode(getFatCode());
        copy.setCookingMethodFacetDescriptorLookupKey(getCookingMethodFacetDescriptorLookupKey());
        copy.setPercentageOfFatAbsorbedDuringCooking(getPercentageOfFatAbsorbedDuringCooking());
        return copy;
    }

    @Property(
            snapshot = Snapshot.EXCLUDED
    )
    @PropertyLayout(
            hidden = Where.EVERYWHERE,
            navigable = Navigable.PARENT
    )
    @NotPersistent
    public PercentOfFatUseDuringCookingForFood.Manager getNavigableParent() {
        return new PercentOfFatUseDuringCookingForFood.Manager(searchService, "");
    }

    /**
     * Manager Viewmodel for @{link PercentOfFatUseDuringCookingForFood}
     */
    @Generated("io.github.causewaystuff.companion.codegen.domgen._GenEntity_Manager")
    @Named("dita.globodiet.params.food_coefficient.PercentOfFatUseDuringCookingForFood.Manager")
    @DomainObject(
            nature = Nature.VIEW_MODEL
    )
    @DomainObjectLayout(
            describedAs = "% of fat use during cooking attached to a food",
            cssClassFa = "solid percent"
    )
    @AllArgsConstructor
    public static final class Manager implements ViewModel {
        public final SearchService searchService;

        @Property(
                optionality = Optionality.OPTIONAL,
                editing = Editing.ENABLED
        )
        @PropertyLayout(
                fieldSetId = "searchBar"
        )
        @Getter
        @Setter
        private String search;

        @ObjectSupport
        public String title() {
            return "Manage Percent Of Fat Use During Cooking For Food";
        }

        @Collection
        public final List<PercentOfFatUseDuringCookingForFood> getListOfPercentOfFatUseDuringCookingForFood() {
            return searchService.search(PercentOfFatUseDuringCookingForFood.class, PercentOfFatUseDuringCookingForFood::title, search);
        }

        @Override
        public final String viewModelMemento() {
            return getSearch();
        }
    }
}
