= Campaign Manager Model

== Survey

A _survey_ collects one or more campaigns.

[plantuml,fig-survey,svg]
.Survey Model
----
@startuml
left to right direction

class Survey {
    objectId¹: String
    name: String
    description: String
}

Survey o--> "1..*" Campaign : collects
hide class method

@enduml
----

<.> objectId: immutable identifier to reference the _Survey_ object

== Campaign

A _campaign_ defines a part of a food consumption survey that contains several interviews. Campaigns can be defined to be the whole study, a seasonal part of a study, a regional part of a study etc. 

A campaign uses a large set of configuration options (_campaign settings_) that make up possible questions and answers for the interviews.

[plantuml,fig-campaign,svg]
.Campaign Model
----
@startuml
left to right direction

class Campaign {
    objectId¹: String
    name: String
    description: String
    startDate²: LocalDate
    endDate²: LocalDate
}

Campaign "1..*" --> "1" "Campaign Settings" : uses
Interview "1..*" --> "1" "Campaign Settings" : uses
Campaign "1" --> "0..n" Interview : collects
hide class method

@enduml
----

<.> objectId: immutable identifier to reference the _Campaign_ object
<.> startDate, endDate: optional, for informal purpose

== Campaign Settings

_Campaign Settings_ are created by taking a snapshot of the current state of the _Parameter Data Model_. The latter is subject to continuous improvements. In contrast, _Campaign Settings_ are fixated for the duration of a campaign run.

[plantuml,fig-campaign-settings,svg]
.Campaign Settings Model
----
@startuml
left to right direction

package "GloboDiet Parameter Data" <<Frame>> #DAE8FC {

    Food --> FoodFacet 
    FoodFacet --> FoodDescriptor
    Recipe --> RecipeFacet 
    RecipeFacet --> RecipeDescriptor
    hide class method
    hide class field
    hide class circle
    
    note as N1
      and many more
    end note

}

class "Campaign Settings" {
    creationTimestamp¹: Instant
    name: String
    description: String
    parameterData²: BlobDescriptor
}

package "Blob Store" <<Database>> {
  object Yaml {
    timestamp
  }
}

"GloboDiet Parameter Data" .left.> "Campaign Settings" : snapshot
"Campaign Settings" o--> Yaml : owns
hide class method

@enduml
----

<.> creationTimestamp: immutable identifier to reference the _Snapshot_ 
- formats with `yyyy-MM-dd--HH-mm`
<.> parameterData: blob-store handle to retrieve the serialized _Parameter Data Model_ 

