= Consumption Reporting
:includedir: includes

In the following chapters we describe the key data structures 
for reporting food consumption data.

== Reporter

Aspects to be considered for the `ReporterService`:

* Filtering - e.g. by respondent alias or by interview date say.
* Nutritional attribute selection - provide choices of `FoodComponent`(s) given a `FoodComponentCatalog`. 
* Aggregation of nutrient values:
** `MEAL` - Sum total of nutrient values for each meal.  
** `INTERVIEW` - Sum total of nutrient values for each interview.
** `RESPONDENT_AVERAGE` - Average of nutrient values for each respondent per interview 
(averaged over all interviews available for a given respondent).
** `RESPONDENT_AVERAGE_GROUP_BY_FOOD_GROUP` - variant that groups by food-group.
** `RESPONDENT_AVERAGE_GROUP_BY_FOOD_GROUP_AND_SUBGROUP` - variant that groups by food-group and food-subgroup.
* Aggregation of Composites - allow for some composites to be reported as single consumption 
(instead of splitting them up into their sub-records, which is the default).
* Language - Translation e.g. in which to express column headers.
* Target `FileFormat` (at least support `EXCEL`).

Requirements:

* Connection to a _Food Composition Database_ (FCDB)

`ReportOptions` are either provided in a static way (configuration) or originate from a data base.

[plantuml,fig-reporter,svg]
.Reporter
----
@startuml

interface ReporterService {
    report(InterviewSet24, ReportOptions): Clob
}

class ReportOptions {
    name: String
    description: String
    language: Locale
}

enum FileFormat {
    JSON
    YAML
    XML
    EXCEL
}

enum NutrientAggregation {
    NONE
    MEAL
    INTERVIEW
    RESPONDENT_AVERAGE
    RESPONDENT_AVERAGE_GROUP_BY_FOOD_GROUP
    RESPONDENT_AVERAGE_GROUP_BY_FOOD_GROUP_AND_SUBGROUP
}

ReporterService .> FoodCompositionRepository : "connected to"
ReporterService ..> ReportOptions : "uses"

ReportOptions -> NutrientAggregation
ReportOptions --> FileFormat
ReportOptions --> "1..*" FoodComponent : "components\n(has one\nor more)"
ReportOptions --> "0..*" SemanticIdentifier : "compositesToAggregate\n(has zero or more)"

@enduml
----

== Interview Set

An `Interview Set` is a set of respondents 
including their interview and consumption data.

[plantuml,fig-interviewset,svg]
.Interview Set
----
@startuml

package "Consumption Data" <<Frame>> #E8DAFC {

    class Meal {
    }
    
    class "Memorized Food" {
    }
    
    interface Record {
    }

    Meal o-d-> "*" "Memorized Food"
    "Memorized Food" o-> "*" Record
    
    Consumption -d-|> Record
    
    hide class circle
    hide class method
    hide enum method
}

InterviewSet o-> "*" Respondent
Respondent o-> "*" Interview
Interview o--> "*" Meal

hide class circle
hide class method
hide enum method

@enduml
----

[NOTE]
====
Perhaps a good design for calling clients 
is to store the reporter's `Clob` results in a `BlobStore`.
====

include::{includedir}/ConsumptionRecord.adoc[leveloffset=1]

== Consumption Correction/Amendment (Draft)

Typically with surveys, some issues with e.g. recipes are discovered only *after* interviews were made. 
It is likely that consumption data will need some correction as post processing step.

=== Consumption Identification

Consumption entries have no identifier per-se, so we need to address specific entries that need corrections
using 2 steps:

. Given a respondent alias and a consumption date, a specific interview file can be identified.
. Given a specific interview file we can locate a contained consumption record using its ordinal within the interview.

On creation of such a `ConsumptionFileAddress` we should also track the interview file version using a hash (e.g. SHA256),
such that we can protect against upstream changes of the file in question.

Corrections are either adding a new consumption entry or deleting an existing consumption entry 
or changing the amount of an existing consumption entry.

[plantuml,fig-cons-corr,svg]
.Consumption Correction
----
@startuml

class ConsumptionFileAddress << (R,orchid) >> {
    respondentId: String 
    consumptionDate: LocalDate
    sha256: String
}

class ConsumptionRecordAddress << (R,orchid) >> {
    consumptionOrdinal: int
}

class ConsumptionCorrection << (R,orchid) >> {
    change: String
}

enum TypeOfChange {
    UPDATE_AMOUNT
    ADD
    DELETE
}

ConsumptionRecordAddress -> ConsumptionFileAddress : fileAddress
ConsumptionCorrection --> ConsumptionRecordAddress : recordAddress
ConsumptionCorrection -> TypeOfChange : typeOfChange

@enduml
----