= Consumption Reporting
:includedir: includes

In the following chapters we describe the key data structures 
for reporting food consumption data.

== Reporter

Aspects to be considered for the `ReporterService`:

* Filtering - e.g. by respondent alias or by interview date say.
* Nutritional attribute selection - provide choices of `FoodComponent`(s) given a `FoodComponentCatalog`. 
* Aggregation of nutrient values:
** `MEAL` - Sum total of nutrient values for each meal.  
** `INTERVIEW` - Sum total of nutrient values for each interview.
** `RESPONDENT_AVERAGE` - Average of nutrient values for each respondent per interview 
(averaged over all interviews available for a given respondent).
** `RESPONDENT_AVERAGE_GROUP_BY_FOOD_GROUP` - variant that groups by food-group.
** `RESPONDENT_AVERAGE_GROUP_BY_FOOD_GROUP_AND_SUBGROUP` - variant that groups by food-group and food-subgroup.
* Aggregation of Composites - allow for some composites to be reported as single consumption 
(instead of splitting them up into their sub-records, which is the default).
* Language - Translation e.g. in which to express column headers.
* Target `FileFormat` (at least support `EXCEL`).

Requirements:

* Connection to a _Food Composition Database_ (FCDB)

`ReportOptions` are either provided in a static way (configuration) or originate from a data base.

[plantuml,fig-reporter,svg]
.Reporter
----
@startuml

interface ReporterService {
    report(InterviewSet24, ReportOptions): Clob
}

class ReportOptions {
    name: String
    description: String
    language: Locale
}

enum FileFormat {
    JSON
    YAML
    XML
    EXCEL
}

enum NutrientAggregation {
    NONE
    MEAL
    INTERVIEW
    RESPONDENT_AVERAGE
    RESPONDENT_AVERAGE_GROUP_BY_FOOD_GROUP
    RESPONDENT_AVERAGE_GROUP_BY_FOOD_GROUP_AND_SUBGROUP
}

ReporterService .> FoodCompositionRepository : "connected to"
ReporterService ..> ReportOptions : "uses"

ReportOptions -> NutrientAggregation
ReportOptions --> FileFormat
ReportOptions --> "1..*" FoodComponent : "components\n(has one\nor more)"
ReportOptions --> "0..*" SemanticIdentifier : "compositesToAggregate\n(has zero or more)"

@enduml
----

== Interview Set

An `Interview Set` is a set of respondents 
including their interview and consumption data.

[plantuml,fig-interviewset,svg]
.Interview Set
----
@startuml

package "Consumption Data" <<Frame>> #E8DAFC {

    class Meal {
    }
    
    class "Memorized Food" {
    }
    
    interface Record {
    }

    Meal o-d-> "*" "Memorized Food"
    "Memorized Food" o-> "*" Record
    
    Consumption -d-|> Record
    
    hide class circle
    hide class method
    hide enum method
}

InterviewSet o-> "*" Respondent
Respondent o-> "*" Interview
Interview o--> "*" Meal

hide class circle
hide class method
hide enum method

@enduml
----

[NOTE]
====
Perhaps a good design for calling clients 
is to store the reporter's `Clob` results in a `BlobStore`.
====

include::{includedir}/ConsumptionRecord.adoc[leveloffset=1]

== Consumption Correction

For surveys it is a typical scenario, that issues with e.g. recipes are only discovered after interviews were made. 
So it is most likely that consumption data will need some correction mechanism, that is, on a per interview basis.

Modeling corrections:

. Consumption entries have no identifier per-se, so how to address a specific entry that needs correction?
. Corrections are either adding a new consumption entry or deleting an existing consumption entry 
or changing the amount of an existing consumption entry
   