= Data Cleaning
:includedir: includes

Typically with surveys, data will be entered incorrectly by interviewers 
or issues with recipes are discovered only *after* interviews had been conducted.
Hence it is likely that respondent and consumption data will need correction as a post processing step.

_Dita_ implements an interview-set transformer, that corrects interview data based on uploaded correction files.
Those correction files have following structure:

[plantuml,fig-corr-overview,svg]
.Correction24
----
@startuml

hide empty fields
hide empty methods

class Correction24 << (R,orchid) >> {
}

class RespondentCorr << (R,orchid) >> {
    alias: String
    withdraw: boolean
    newAlias: String
    dateOfBirth: LocalDate
}

enum Sex {
    UNCLASSIFIED
    MALE
    FEMALE
}

RespondentCorr --> Sex : sex

class FoodByNameCorr << (R,orchid) >> {
    name: String
    sid: SemanticIdentifier
}

class CompositeCorr << (R,orchid) >> {
    rename: String
}

class Coordinates << (R,orchid) >> {
    sid: SemanticIdentifier
    respondentId: String
    interviewOrdinal: int
    mealHourOfDay: LocalTime
    source: NamedPath 
}

class Addition << (R,orchid) >> {
    sid: SemanticIdentifier
    amountGrams: BigDecimal
    facets: SemanticIdentifierSet
}

class Deletion << (R,orchid) >> {
    sid: SemanticIdentifier
}

Correction24 --> "*" RespondentCorr: respondents
Correction24 --> "*" FoodByNameCorr: foodByName
Correction24 --> "*" CompositeCorr: composites
CompositeCorr --> "1" Coordinates: coordinates
CompositeCorr --> "*" Addition: additions
CompositeCorr --> "*" Deletion: deletions

@enduml
----

[source,yaml]
.Correction YAML basic structure
----
respondents:
- alias: "EB_9999"
  #...
# and so on ...  
foodByName:
- name: "Maiswaffeln"
  sid: "at.gd/2.0:food/02423"
# and so on ...  
composites:
- coordinates:
    #...
  rename: # optional: new name or empty or omitted
  deletions:
    #...
  additions:
    #...
# and so on ...    
----

== Respondent Correction

Allows to correct defect data entered during interview such as the _Respondent-Id_, _Sex_ or _Date of Birth_.
Also allows to remove interviews from respondents, that later wished to withdraw from the survey.

[plantuml,fig-corr-resp,svg]
.Respondent correction
----
@startuml

hide empty fields
hide empty methods

class RespondentCorr << (R,orchid) >> {
    alias: String
    withdraw: boolean
    newAlias: String
    dateOfBirth: LocalDate
}

enum Sex {
    UNCLASSIFIED
    MALE
    FEMALE
}

RespondentCorr -> Sex : sex

@enduml
----

Some examples:  

[source,yaml]
.Fixing respondent-id typo
----
respondents:
- alias: "EB9999"
  newAlias: "EB_9999"
----

[source,yaml]
.Fixing respondent-data
----
respondents:
- alias: "EB_9999"
  dateOfBirth: 1999-11-22
  sex: MALE
----

[source,yaml]
.Respondent withdrawal
----
respondents:
- alias: "EB_9999"
  withdraw: true
----

== Consumption Correction

=== Food

Correcting food consumptions, that have no identifier, only a name.

[plantuml,fig-corr-foodbyname,svg]
.Food by name correction
----
@startuml

hide empty fields
hide empty methods

class FoodByNameCorr << (R,orchid) >> {
    name: String
    sid: SemanticIdentifier
}

@enduml
----

[source,yaml]
.Fixes food with missing identifier (having a name but no sid)
----
foodByName:
- name: "Maiswaffeln"
  sid: "at.gd/2.0:food/02423"
----

=== Composite

Correction of composite consumptions supports 3 basic changes:

* Renaming of the composite consumption entry 
* *ADD* Ingredient: 
** requires identifier (`sid`) of food to add
** requires `amountGrams` of food to add
** requires `facets` of food to add
* *DELETE* Ingredient: 
** requires identifier (_sid_) of food to remove

After those changes are applied, all the ingredient amounts are recalculated 
such that the composite's total amount consumed stays the same (as compared to before the correction). 

[plantuml,fig-corr-comp,svg]
.Composite correction
----
@startuml

hide empty fields
hide empty methods

class CompositeCorr << (R,orchid) >> {
    rename: String
}

class Coordinates << (R,orchid) >> {
    sid: SemanticIdentifier
    respondentId: String
    interviewOrdinal: int
    mealHourOfDay: LocalTime
    source: NamedPath 
}

class Addition << (R,orchid) >> {
    sid: SemanticIdentifier
    amountGrams: BigDecimal
    facets: SemanticIdentifierSet
}

class Deletion << (R,orchid) >> {
    sid: SemanticIdentifier
}

CompositeCorr --> "1" Coordinates: coordinates
CompositeCorr --> "*" Addition: additions
CompositeCorr --> "*" Deletion: deletions

@enduml
----

[source,yaml]
.Fixes a composite consumption by deleting and adding specific ingredients
----
composites:
- coordinates: 
    sid: "at.gd/2.0:recp/00514"
    respondentId: "EB_9999"
    interviewOrdinal: 1
    mealHourOfDay: "13:00:00"
    source: "wave1/Interview-12345.xml"
  deletions: 
    # DELETE food/02280 Fond, Fleisch {assocRecp=465} 413.56g (82.71%)
  - sid: "at.gd/2.0:food/02280"
  additions: 
    # ADD food/01399 Wasser, Leitung 302,72g
  - sid: "at.gd/2.0:food/01399"
    amountGrams:  302.72
    facets: ""
    # ADD food/01581 Streuwürze 6,05g
  - sid: "at.gd/2.0:food/01581"
    amountGrams:  6.05
    facets: ""
----

[source,yaml]
.Changes a composite consumption name
----
composites:
- coordinates: 
    sid: "at.gd/2.0:recp/00514"
    respondentId: "EB_9999"
    interviewOrdinal: 1
    mealHourOfDay: "13:00:00"
    source: "wave1/Interview-12345.xml"
  rename: "New Name"
  deletions: [] 
  additions: []
----

== Consumption Identification

[plantuml,fig-corr-coors,svg]
.Composite coordinates
----
@startuml

hide empty fields
hide empty methods

class Coordinates << (R,orchid) >> {
    sid: SemanticIdentifier
    respondentId: String
    interviewOrdinal: int
    mealHourOfDay: LocalTime
    source: NamedPath 
}

@enduml
----

Consumption entries have no identifier per-se, so we use multiple *coordinates* to narrow down specific entries:

* `sid`: SemanticIdentifier of the recipe in question
* `respondentId`
* `interviewOrdinal`
* `mealHourOfDay`
* `source`: path of the interview source file in question

NOTE: Special care needs to be taken when uploading new interview data, 
as this may render those coordinates invalid. It may also render any of the above corrections invalid!

== Working with multiple Correction Files

Multiple correction files can be uploaded each representing a `Correction24` data structure. 
_Dita_ automatically collects these into a single `Correction24` object for interview data post processing.

Here are some templates:

[source,yaml]
.only correcting respondents
----
respondents:
- alias: "EB_9999"
  #...
# and so on ...
foodByName: []
composites: []
----

[source,yaml]
.only correcting composite consumptions
----
respondents: []
foodByName: []
composites:
- coordinates:
    #...
  rename: # optional: new name or empty or omitted
  deletions:
    #...
  additions:
    #...
# and so on ...     
----
  