= Food Model Mapping

In the following chapters we describe the basic principles used for mapping from arbitrary _food models_ to others. 
And in particular matching _Food Consumption Data_ with _Food Composition Data_.

== Generic Types

=== Semantic Identifier

A _Semantic Identifier_ (SID) references data objects across system boundaries.

[plantuml,fig-sid,svg]
.Semantic Identifier (SID)
----
@startuml

class SemanticIdentifier {
    systemId: String
    objectId: String
}

class SemanticIdentifierSet {
}

note right of SemanticIdentifier::systemId
  identifies the system (and optionally system version) of the referenced data object
end note
note right of SemanticIdentifier::objectId
  uniquely identifies the data object within the system
end note

SemanticIdentifierSet -right-> "*" SemanticIdentifier : has many

hide class method

@enduml
----

Example use, referencing a food, product or facet.

[source,java]
.Java
----
// within BLS v3.02 represents 'Banana raw'
var blsBananaId = new SemanticIdentifier("BLS302", "F503100");

// within LanguaL 2017 Facet Category - A (PRODUCT TYPE) represents 'Bananas' from GS1 ontology
var gs1BananaId = new SemanticIdentifier("LanguaL2017", "A1415"); 
----

=== Qualified Map

A _Qualified Map Entry_ relates data objects from one system to another, optionally respecting _qualifiers_, 
that allow for fine-grained conditionals like _facet term codes_ (FTCs).  

[plantuml,fig-qualifiedmap,svg]
.Qualified Map Entry
----
@startuml

class QualifiedMapEntry {
    source: SemanticIdentifier
    qualifier: SemanticIdentifierSet
    target: SemanticIdentifier
}

note right of QualifiedMapEntry::source
  semantic identifier of the data object that is mapped from
end note
note right of QualifiedMapEntry::qualifier
  constraints under which this mapping entry is applicable; e.g. food facet terms
end note
note right of QualifiedMapEntry::target
  semantic identifier of the data object that is mapped to
end note

QualifiedMap -right-> "*" QualifiedMapEntry : has many

hide class method

@enduml
----

Example use, adding a map-entry, then looking it up.

[source,java]
.Java
----
// food consumption descriptors 
SemanticIdentifier consumedBananaId = ...
SemanticIdentifierSet facets = ...

// food composition database entry reference
SemanticIdentifier fcdbBananaId = ...

var qMap = new QualifiedMap();

// puts a new entry into the map 
qMap.put(new QualifiedMapEntry(consumedBananaId, facets, fcdbBananaId));

// lookup entries
Optional<QualifiedMapEntry> result = qMap.lookupEntry(consumedBananaId, facets);
----

== Food Composition Database (FCDB)

=== Food Component Catalog and Components 

A _Food Component Catalog_ collects all available food components, that are
within the scope of a food composition database (FCDB).

A _Food Component_ represents a chemical substance (e.g. Carbohydrates) or other food component or other 
food specific value, that in some cases is independent of the consumed amount 
e.g. 'recommended daily dosage' or 'protein animal to plant ratio'. 


[plantuml,fig-foodcomponent,svg]
.Food Component Catalog and Components
----
@startuml

class FoodComponent {
    componentId: SemanticIdentifier
}

enum ComponentUnit {
    ONE
    RATIO¹
    PERCENT¹
    CALORIES
    JOUL
    GRAM
    BREAD_EXCHANGE
}

enum MetricPrefix {
    KILO
    MILLI
    MICRO
    ..
    etc.
}

note right of FoodComponent::componentId
  semantic identifier of this component
end note

FoodComponentCatalog -right-> "*" FoodComponent : has many
FoodComponent --> ComponentUnit: has a metric unit
FoodComponent --> MetricPrefix : has a preferred metric prefix\nwhen displaying the quantified value\nof this component

hide class method
hide enum method

@enduml
----
  
<.> Component units *RATIO* and *PERCENT* indicate that the component is invariant with respect to the amount consumed.

Example use, adding a food component to its catalog, then looking it up.

[source,java]
.Java
----
var componentCatalog = new FoodComponentCatalog();

// food component identifier
SemanticIdentifier componentId = ...

// puts a new food component into the catalog
componentCatalog.put(new FoodComponent(componentId, ComponentUnit.GRAM, MetricPrefix.MILLI));

// lookup a food component by its semantic identifier
Optional<FoodComponent> result = componentCatalog.lookupEntry(componentId);
----

=== Food Composition and Datapoints

A _Food Composition_ represents a collection of data-points for a specific food.

A _Food Component Datapoint_ represents a measured or calculated value for the relative mass amount 
of a chemical substance or other food component or simply a food specific fixed value 
like 'recommended daily dosage' or 'protein animal to plant ratio'.


[plantuml,fig-foodcompdata,svg]
.Food Composition and Datapoints
----
@startuml

class FoodComposition {
    foodId: SemanticIdentifier
}

class FoodComponentDatapoint {
    datapointValue¹: BigDecimal
}

enum ConcentrationUnit {
    PER_100_GRAM
    PER_100_MILLILITER
    PER_PART
}

enum DatapointSemantic {
    AS_IS
    UPPER_BOUND
}

note right of FoodComponentDatapoint::datapointValue
  the concentration amount or fixed value of the data-point
end note

FoodComposition -> "*" FoodComponentDatapoint : has many
FoodComposition --> ConcentrationUnit : has one¹

FoodComponentDatapoint --> FoodComponent : has one, which it relates to 
FoodComponentDatapoint --> DatapointSemantic : has one²
FoodComponentDatapoint --> CompositionQuantification : has one¹

hide class method
hide enum method

@enduml
----

<.> *ConcentrationUnit*: how to quantify the amount of dietary components consumed for this associated food (or product)
<.> *DatapointSemantic*: how the datapoint is interpreted (as-is or as upper-bound)

=== Food Composition Repository

A _Food Composition Repository_ incorporates
 
* a food component catalog and
* many food compositions with their datapoints.

[plantuml,fig-foodcomprepo,svg]
.Food Composition Repository
----
@startuml

class FoodCompositionRepository {
}

FoodCompositionRepository --> FoodComponentCatalog : has one
FoodCompositionRepository -> "*" FoodComposition : has many

hide class method

@enduml
----

Example use, loading data model from zipped yaml file, then lookup an entry.

[source,java]
.Java
----
import org.apache.causeway.commons.io.DataSource;
import io.github.causewaystuff.commons.compression.SevenZUtils;

// decompress data source from zipped yaml file
DataSource foodCompositionDataSource = SevenZUtils
    .decompress(DataSource.ofFile("fcdb.7z"));   
    
// read in data    
var foodCompositionRepo = FoodCompositionRepository.tryFromYaml(foodCompositionDataSource)
    .valueAsNonNullElseFail();

// food identifier
SemanticIdentifier foodId = ...

// lookup a food composition entry by its semantic food identifier
Optional<FoodComposition> result = foodCompositionRepo.lookupEntry(foodId);
----

== Food Consumption and Composition Resolution

=== Food Consumption

A _Food Composition_ represents an amount of some food or product that was consumed.

[plantuml,fig-foodconsumption,svg]
.Food Consumption
----
@startuml

class FoodConsumption {
    foodId: SemanticIdentifier
    facetIds: SemanticIdentifierSet
    amountConsumed: BigDecimal
}

enum ConsumptionUnit {
    GRAM
    MILLILITER
    PART
}

FoodConsumption -> ConsumptionUnit : amount consumed\nis given in units of

hide class method
hide enum method

@enduml
----

=== Food Consumption with Composition

A _Food Consumption with Composition_ relates consumption with composition information. 
Instances are usually the result of food composition resolution. (see below) 

[plantuml,fig-foodconsumptionwcomp,svg]
.Food Consumption with Composition
----
@startuml

class FoodConsumptionWithComposition {
}

class FoodComponentQuantified {
    quantity: Quantity
}

FoodConsumptionWithComposition -left-> FoodConsumption : has one
FoodConsumptionWithComposition -right-> FoodComposition : has one

FoodConsumptionWithComposition ..> FoodComponentQuantified : provides quantified food components
FoodComponentQuantified -> FoodComponent : has one

hide class method

@enduml
----

=== Food Composition Resolution (via Nutrient Mapping)

Food consumption data (typically originating from recall 24 interviews) is mapped to a food composition database, 
that provides (measured or estimated) chemical food component quantities for a given specific food.

In effect, consumed quantities of food X can be resolved to consumed quantities of nutrients A, B, C, etc..   

[plantuml,fig-mapping,svg]
.Food Composition Resolution
----
@startuml

class Interview {
    respondentAlias¹: String
    date²: LocalDate
}

class FoodConsumption {
    foodId: SemanticIdentifier
    facetIds: SemanticIdentifierSet
 }

class QualifiedMapEntry {
    source: SemanticIdentifier
    qualifier: SemanticIdentifierSet
    target: SemanticIdentifier
}

class FoodComposition {
    foodId: SemanticIdentifier
}

Interview o-> "*" FoodConsumption : collects
FoodConsumption -> QualifiedMapEntry : mapped by
QualifiedMapEntry -> FoodComposition : maps to

FoodConsumptionWithComposition ..> FoodComposition : is constructed by
FoodConsumptionWithComposition ..> FoodConsumption : is constructed by

hide class method

@enduml
----

<.> *respondentAlias*: first part of the secondary object identifier
<.> *date*: second part of the secondary object identifier