= Interview Model
:includedir: includes

In the following chapters we describe the key data structures for capturing food consumption data.

== Respondent

A _respondent_ is the subject of at least one interview.

[plantuml,fig-respondent,svg]
.Respondent Model
----
@startuml

class Respondent {
    alias: String
    dateOfBirth: LocalDate
    age(referenceDate: LocalDate)
}

note right of Respondent::alias
  campaign scoped identifier to uniquely reference the respondent
end note
note right of Respondent::age
  calculated value, based on the 'referenceDate' argument
end note

Respondent --> "*" Interview : answers to \none or more
hide Interview method

@enduml
----

== Interview

An _interview_ is a set of questions and answers attributed to a person (respondent). It specifically collects consumption data from a single day.

[plantuml,fig-interview,svg]
.Interview Model
----
@startuml

class Interview {
    objectId: String
    consumptionDate: LocalDate
    interviewOrdinal: int
    interviewDate: LocalDate
}

package "Consumption Data" <<Frame>> #E8DAFC {

    class Meal {
        hourOfDay: LocalTime
        foodConsumptionOccasion: String 
        foodConsumptionPlace: String 
    }
    
    class "Memorized Food" {
        name: String
    }
    
    interface Record {
        foodId: SemanticIdentifier
        facetIds: SemanticIdentifierSet
        name: String
        description: String
    }

    Meal o--> "*" "Memorized Food"  : has one \nor more
    "Memorized Food" o--> "*" Record : has one \nor more \ntop-level
    
    Composite --|> Record : "        "
    Composite o-> "*" Record : subRecords
    
    ConsumptionRecord -l-|> Record
    Food -d-|> ConsumptionRecord
    FryingFat -d-|> ConsumptionRecord
    Product -d-|> ConsumptionRecord
    
    
    hide class circle
    hide class method
    hide enum method
}

class "Respondent\nSupplementary Data" <<Map>> {
    height[cm]: decimal
    weight[kg]: decimal
    specialDay: String
    specialDiet: String
    .. etc.
}

Campaign o--> Interview : collects
Respondent --> Interview : answers to
Interview o-left-> "Respondent\nSupplementary Data": collects
Interview o-down-> Meal : collects\n\n
hide class method

note right of Interview::objectId
  campaign scoped identifier to uniquely reference the interview
  e.g. respondent alias and consumption date
end note


@enduml
----

include::{includedir}/ConsumptionRecord.adoc[leveloffset=1]

== APPENDIX

=== Interview Data Structure Requirements

The data structure forms a tree, starting from its root followed by _respondent_ nodes followed by _interview_ nodes and so on.

* *Serializable.* It should be possible to serialize the entire tree to XML, JSON or YAML 
and deserialize likewise.
 
* *Transformable.* Starting from a given tree, 
it should be possible to create a new tree that has some selected nodes modified.
 
* *Navigable.* For every node in the tree we want to be able to navigate to its parent node or child nodes.

* *Immutable.* Modification of the tree (once created), should not be possible unless by means of a transformer.

=== GloboDiet Interview Export Semantics

The following table shows correspondence between fields from the _GloboDiet_ export files and our record model. 

.GloboDiet Interview Export Semantics
[cols="1m,1m,1m,4a",width="100%"]
|===
.2+h|*Record Model* 3+h|*GloboDiet*
|*XML* (LigneITV tag) |*CSV* (INTERV File) | *Description*

|Record.*foodId* +
(SemanticIdentifier)
|ITL_FoodNum
|FOODNUM
|_Food_ or _Recipe_ or _Product_ code. *Empty* for ad-hoc recipes (e.g. `R_TYPE=4.1` .. `New Unknown`). 

|Record.*facetIds* +
(SemanticIdentifierSet)
|ITL_Facets_STR
|FACETS_STR
|Sequence of Facets/Descriptors codes delimited by comma (ffdd,ffdd,ffdd,... e.g. “0401,0304”)

|Record.*name* +
(String)
|ITL_Name
|NAME
|_Food_ or _Recipe_ or _Product_ name.

|Record.*description* +
(String)
|ITL_Text
|TEXT
|_Food_ or _Recipe_ or _Product_ description.

|ConsumptionRecord +
.*amountConsumed* +
(BigDecimal)
|ITL_CONS_QTY
|CONS_QTY
|Consumed quantity in grams (after having applied conversion factors).

|ConsumptionRecord +
.*rawPerCookedRatio* +
(BigDecimal)
|ITL_CONVER
|CONVER
|Raw to cooked coefficient.

|===
