= Recipe Management
:includedir: includes

Recipes are managed with _GloboDiet Recipe Manager_. The process involves several steps:

. Nutrition expert uses _GloboDiet_ to restore the most recent database backup, 
that can be downloaded from the _Dita_ `Versions` menu.
. Nutrition expert applies desired changes to recipes within _GloboDiet Recipe Manager_.
. Nutrition expert creates a recipe XML export and sends it to the system administrator.
. System administrator imports the recipe XML into reference MS SQL server.
. System administrator replicates database from reference MS SQL server into _Dita_.
. System administrator creates a new `Version` in _Dita_ 
that documents changes 
and provides a new _GloboDiet_ database backup file for download.

[plantuml,fig-recipe-exchange,svg]
.Recipe data exchange
----
@startuml

actor       NutExpert as "Nutrition\nExpert" 
boundary    RecipeManager as "GloboDiet\nRecipe Manager"
actor       SysAdmin as "System\nAdmin"
boundary    Dita
database    RefDB as "Reference\nMS SQL"

NutExpert -> Dita : get latest BAK\nfrom Dita Versions
NutExpert <- Dita
NutExpert -> RecipeManager : restore latest BAK
NutExpert -> RecipeManager : apply changes to recipes
NutExpert -> RecipeManager : creates a recipe XML export
NutExpert <- RecipeManager
NutExpert -> SysAdmin : sends recipe XML export
SysAdmin  -> RefDB : imports recipes
SysAdmin  -> Dita : issues database replication
Dita      --> RefDB: table data request
Dita      <- RefDB : table data response
SysAdmin  -> Dita : creates new Version\nwith new BAK

@enduml
----