/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Auto-generated by Causeway-Stuff code generator.
package dita.globodiet.params.pathway;

import io.github.causewaystuff.companion.applib.jpa.EnumConverter;
import io.github.causewaystuff.companion.applib.jpa.EnumWithCode;
import io.github.causewaystuff.companion.applib.jpa.Persistable;
import io.github.causewaystuff.companion.applib.services.lookup.Cloneable;
import io.github.causewaystuff.companion.applib.services.search.SearchService;
import jakarta.inject.Inject;
import jakarta.inject.Named;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import javax.annotation.processing.Generated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.apache.causeway.applib.ViewModel;
import org.apache.causeway.applib.annotation.Collection;
import org.apache.causeway.applib.annotation.DomainObject;
import org.apache.causeway.applib.annotation.DomainObjectLayout;
import org.apache.causeway.applib.annotation.Editing;
import org.apache.causeway.applib.annotation.Nature;
import org.apache.causeway.applib.annotation.Navigable;
import org.apache.causeway.applib.annotation.ObjectSupport;
import org.apache.causeway.applib.annotation.Optionality;
import org.apache.causeway.applib.annotation.Programmatic;
import org.apache.causeway.applib.annotation.Property;
import org.apache.causeway.applib.annotation.PropertyLayout;
import org.apache.causeway.applib.annotation.Snapshot;
import org.apache.causeway.applib.annotation.Where;
import org.apache.causeway.applib.services.repository.RepositoryService;

/**
 * Quantification method pathway for individual recipe.
 * Supersedes this recipe's group quantification method pathway from @{table QM_RCLAS}.
 */
@Generated("io.github.causewaystuff.companion.codegen.domgen._GenEntity")
@Named("dita.globodiet.params.pathway.QuantificationMethodPathwayForRecipe")
@DomainObject
@DomainObjectLayout(
        describedAs = "Quantification method pathway for individual recipe.\n"
                + "Supersedes this recipe's group quantification method pathway from @{table QM_RCLAS}.",
        cssClassFa = "solid person-walking-arrow-right .recipe-color,\n"
                + "solid scale-balanced .recipe-color .ov-size-60 .ov-right-50 .ov-bottom-85,\n"
                + "solid exclamation-circle .recipe-color-em .ov-size-60 .ov-left-50 .ov-bottom-85\n"
)
@Entity
@Table(
        name = "QM_RECIP"
)
public class QuantificationMethodPathwayForRecipe implements Persistable, Cloneable<QuantificationMethodPathwayForRecipe> {
    @Inject
    @Transient
    RepositoryService repositoryService;

    @Inject
    @Transient
    SearchService searchService;

    @Id
    @GeneratedValue(
            strategy = GenerationType.IDENTITY
    )
    private long id;

    /**
     * Recipe identification number (R_IDNUM)
     */
    @Property(
            optionality = Optionality.MANDATORY
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "1",
            describedAs = "Recipe identification number (R_IDNUM)",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "\"ID_NUM\"",
            nullable = false,
            length = 5
    )
    @Getter
    @Setter
    private String recipeCode;

    /**
     * Quantification method code:
     * 'P' for photo,
     * 'H' for HHM,
     * 'U' for stdu,
     * 'A' Shape
     */
    @Property(
            optionality = Optionality.MANDATORY,
            editing = Editing.ENABLED
    )
    @PropertyLayout(
            fieldSetId = "details",
            sequence = "2",
            describedAs = "Quantification method code:\n"
                    + "'P' for photo,\n"
                    + "'H' for HHM,\n"
                    + "'U' for stdu,\n"
                    + "'A' Shape"
    )
    @Column(
            name = "\"METHOD\"",
            nullable = false,
            length = 1
    )
    @Getter
    @Setter
    @Convert(
            converter = QuantificationMethod.Converter.class
    )
    private QuantificationMethod quantificationMethod;

    /**
     * if method='P' Photo code
     * if method='A' Shape code
     * else empty
     */
    @Property(
            optionality = Optionality.OPTIONAL
    )
    @PropertyLayout(
            fieldSetId = "foreign",
            sequence = "3",
            describedAs = "if method='P' Photo code\n"
                    + "if method='A' Shape code\n"
                    + "else empty",
            hidden = Where.ALL_TABLES
    )
    @Column(
            name = "\"METH_CODE\"",
            nullable = true,
            length = 4
    )
    @Getter
    @Setter
    private String photoOrShapeCode;

    @ObjectSupport
    public String title() {
        return this.toString();
    }

    @Override
    public String toString() {
        return "QuantificationMethodPathwayForRecipe(" + "recipeCode=" + getRecipeCode() + ","
         +"quantificationMethod=" + getQuantificationMethod() + ","
         +"photoOrShapeCode=" + getPhotoOrShapeCode() + ")";
    }

    @Programmatic
    @Override
    public QuantificationMethodPathwayForRecipe copy() {
        var copy = repositoryService.detachedEntity(new QuantificationMethodPathwayForRecipe());
        copy.setRecipeCode(getRecipeCode());
        copy.setQuantificationMethod(getQuantificationMethod());
        copy.setPhotoOrShapeCode(getPhotoOrShapeCode());
        return copy;
    }

    @Property(
            snapshot = Snapshot.EXCLUDED
    )
    @PropertyLayout(
            hidden = Where.EVERYWHERE,
            navigable = Navigable.PARENT
    )
    @Transient
    public QuantificationMethodPathwayForRecipe.Manager getNavigableParent() {
        return new QuantificationMethodPathwayForRecipe.Manager(searchService, "");
    }

    @Getter
    @Accessors(
            fluent = true
    )
    @RequiredArgsConstructor
    public enum QuantificationMethod implements EnumWithCode<String> {

        /**
         * no description
         */
        PHOTO("P", "Photo"),
        /**
         * no description
         */
        HOUSEHOLD_MEASURE("H", "Household Measure"),
        /**
         * no description
         */
        STANDARD_UNIT("U", "Standard Unit"),
        /**
         * no description
         */
        SHAPE("A", "Shape");

        private final String code;

        private final String title;

        @jakarta.persistence.Converter
        public static final class Converter implements EnumConverter<QuantificationMethod, String> {
            @Override
            public QuantificationMethod[] values() {
                return QuantificationMethod.values();
            }
        }
    }

    /**
     * Manager Viewmodel for @{link QuantificationMethodPathwayForRecipe}
     */
    @Generated("io.github.causewaystuff.companion.codegen.domgen._GenEntity_Manager")
    @Named("dita.globodiet.params.pathway.QuantificationMethodPathwayForRecipe.Manager")
    @DomainObject(
            nature = Nature.VIEW_MODEL
    )
    @DomainObjectLayout(
            describedAs = "Quantification method pathway for individual recipe.\n"
                    + "Supersedes this recipe's group quantification method pathway from @{table QM_RCLAS}.",
            cssClassFa = "solid person-walking-arrow-right .recipe-color,\n"
                    + "solid scale-balanced .recipe-color .ov-size-60 .ov-right-50 .ov-bottom-85,\n"
                    + "solid exclamation-circle .recipe-color-em .ov-size-60 .ov-left-50 .ov-bottom-85\n"
    )
    @AllArgsConstructor
    public static final class Manager implements ViewModel {
        public final SearchService searchService;

        @Property(
                optionality = Optionality.OPTIONAL,
                editing = Editing.ENABLED
        )
        @PropertyLayout(
                fieldSetId = "searchBar"
        )
        @Getter
        @Setter
        private String search;

        @ObjectSupport
        public String title() {
            return "Manage Quantification Method Pathway For Recipe";
        }

        @Collection
        public final List<QuantificationMethodPathwayForRecipe> getListOfQuantificationMethodPathwayForRecipe() {
            return searchService.search(QuantificationMethodPathwayForRecipe.class, QuantificationMethodPathwayForRecipe::title, search);
        }

        @Override
        public final String viewModelMemento() {
            return getSearch();
        }
    }
}
