/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Auto-generated by Causeway-Stuff code generator.
package dita.globodiet.cleaner.dom;

import org.apache.causeway.applib.annotation.Action;
import org.apache.causeway.applib.annotation.ActionLayout;
import org.apache.causeway.applib.annotation.ActionLayout.Position;
import org.apache.causeway.applib.annotation.MemberSupport;
import org.apache.causeway.applib.annotation.Optionality;
import org.apache.causeway.applib.annotation.Parameter;
import org.apache.causeway.applib.annotation.ParameterLayout;

import lombok.RequiredArgsConstructor;

@Action
@ActionLayout(
        sequence = "1",
        associateWith = "instructionView",
        position = Position.PANEL,
        describedAs = "Edit YAML formatted instructions for the interview postprocessing logic."
)
@RequiredArgsConstructor
public class ConsumptionDataDefect_editInstruction {

    private final ConsumptionDataDefect mixee;

    @MemberSupport
    public ConsumptionDataDefect act(
            @Parameter(optionality = Optionality.OPTIONAL)
            @ParameterLayout(multiLine = 24)
            final String instruction) {
        mixee.setInstruction(instruction);
        return mixee;
    }

    @MemberSupport
    public String defaultInstruction() {
        return mixee.getInstruction();
    }

    @MemberSupport
    public String validateInstruction(final String instruction) {
        return null; //TODO implement
//            Correction24.tryFromYaml(correction)
//            .mapSuccessAsNullable(_->(String)null)
//            .mapFailureToSuccess(e->e.getMessage())
//            .getValue()
//            .orElse(null);
    }

}
