/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Auto-generated by DitA-Tooling
package dita.globodiet.survey;

import org.causewaystuff.blobstore.applib.BlobStore;
import org.causewaystuff.blobstore.applib.BlobStoreFactory;
import org.causewaystuff.commons.base.types.NamedPath;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

import dita.globodiet.survey.entities.SurveyManager_addSurvey;
import dita.globodiet.survey.entities.Survey_addCampaign;
import dita.globodiet.survey.util.InterviewUtils;
import dita.globodiet.survey.view.SurveyTreeNode;
import dita.globodiet.survey.view.SurveyTreeNodeFactory;
import dita.globodiet.survey.view.SurveyVM;
import dita.recall24.model.InterviewSet24;

@Configuration
@Import({
    SurveyVM.class,
    BlobStoreFactory.class,
    
    // non-gen mixins
    SurveyManager_addSurvey.class,
    Survey_addCampaign.class,
        })
@EnableConfigurationProperties({ModuleConfig.SurveyConfiguration.class})
//@ComponentScan(basePackageClasses = Survey.class)
public class ModuleConfig {
    
    @ConfigurationProperties(DitaModuleGdSurvey.NAMESPACE)
    public static record SurveyConfiguration(
            BlobStoreFactory.BlobStoreConfiguration blobstore) {
    }

    @Bean @Qualifier("survey")
    public BlobStore surveyBlobStore(
            final BlobStoreFactory blobStoreFactory,
            final SurveyConfiguration surveyConfiguration) {
        return blobStoreFactory.createBlobStore(surveyConfiguration.blobstore());
    }

    @Bean
    public SurveyTreeNode surveyTreeRootNode(@Qualifier("survey") final BlobStore surveyBlobStore) {

        if(surveyBlobStore==null) {
            return SurveyTreeNodeFactory.emptyNode();
        }

        return InterviewUtils.streamSources(surveyBlobStore, NamedPath.empty(), true)
            .limit(1)
            .map(InterviewUtils::parse)
            .reduce(InterviewSet24::join)
            .map(InterviewSet24::normalized)
            .map(SurveyTreeNodeFactory::surveyNode)
            .orElseGet(SurveyTreeNodeFactory::emptyNode);
    }

}
