/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Auto-generated by DitA-Tooling
package dita.globodiet.survey;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

import dita.globodiet.survey.dom.Survey;
import dita.globodiet.survey.view.SurveyTreeHelperService;
import dita.globodiet.survey.view.SurveyVM;
import dita.globodiet.survey.view.SurveyVM_addIngredient;
import dita.globodiet.survey.view.SurveyVM_deleteIngredient;
import dita.globodiet.survey.view.SurveyVM_editAmount;
import dita.recall24.dto.DitaModuleRecall24Dto;
import dita.recall24.reporter.DitaModuleRecall24Reporter;
import io.github.causewaystuff.blobstore.applib.BlobStore;
import io.github.causewaystuff.blobstore.applib.BlobStoreFactory;

@Configuration
@Import({
    SurveyVM.class,
    SurveyVM_editAmount.class,
    SurveyVM_addIngredient.class,
    SurveyVM_deleteIngredient.class,
    BlobStoreFactory.class,
    SurveyTreeHelperService.class,
    DitaModuleRecall24Dto.class,
    DitaModuleRecall24Reporter.class,
})
@EnableConfigurationProperties({ModuleConfig.SurveyConfiguration.class})
@ComponentScan(basePackageClasses = Survey.class)
public class ModuleConfig {

    @ConfigurationProperties(DitaModuleGdSurvey.NAMESPACE)
    public static record SurveyConfiguration(
            BlobStoreFactory.BlobStoreConfiguration blobstore) {
    }

    @Bean @Qualifier("survey")
    public BlobStore surveyBlobStore(
            final BlobStoreFactory blobStoreFactory,
            final SurveyConfiguration surveyConfiguration) {
        return blobStoreFactory.createBlobStore(surveyConfiguration.blobstore());
    }

}
