/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 */
// Auto-generated by DitA-Tooling
package dita.globodiet.dom.params.recipe_description;

import jakarta.inject.Named;
import java.lang.Integer;
import java.lang.String;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.DatastoreIdentity;
import javax.jdo.annotations.PersistenceCapable;
import lombok.Getter;
import lombok.Setter;
import org.apache.causeway.applib.annotation.DomainObject;
import org.apache.causeway.applib.annotation.DomainObjectLayout;
import org.apache.causeway.applib.annotation.Property;
import org.apache.causeway.applib.annotation.PropertyLayout;

/**
 * Cross reference between Recipe (sub)group and Facet/Descriptor (default pathway)
 */
@Named("dita.globodiet.params.recipe_description.CrossReferenceBetweenRecipeSubGroupAndFacetDescriptor")
@DomainObject
@DomainObjectLayout(
    describedAs = "Cross reference between Recipe (sub)group and Facet/Descriptor (default pathway)"
)
@PersistenceCapable(
    table = "R_GROUPFAC"
)
@DatastoreIdentity(
    strategy = javax.jdo.annotations.IdGeneratorStrategy.IDENTITY,
    column = "id"
)
public class CrossReferenceBetweenRecipeSubGroupAndFacetDescriptor {
  /**
   * Recipe group code
   */
  @Property
  @PropertyLayout(
      sequence = "1",
      describedAs = "Recipe group code"
  )
  @Column(
      name = "RGROUP",
      allowsNull = "true",
      length = 2
  )
  @Getter
  @Setter
  private String recipeGroupCode;

  /**
   * Recipe Subgroup code
   */
  @Property
  @PropertyLayout(
      sequence = "2",
      describedAs = "Recipe Subgroup code"
  )
  @Column(
      name = "RSUBGROUP",
      allowsNull = "true",
      length = 2
  )
  @Getter
  @Setter
  private String recipeSubgroupCode;

  /**
   * Recipe Facet code
   */
  @Property
  @PropertyLayout(
      sequence = "3",
      describedAs = "Recipe Facet code"
  )
  @Column(
      name = "RFACET_CODE",
      allowsNull = "true",
      length = 2
  )
  @Getter
  @Setter
  private String recipeFacetCode;

  /**
   * Recipe Descriptor code
   */
  @Property
  @PropertyLayout(
      sequence = "4",
      describedAs = "Recipe Descriptor code"
  )
  @Column(
      name = "RDESCR_CODE",
      allowsNull = "true",
      length = 2
  )
  @Getter
  @Setter
  private String recipeDescriptorCode;

  /**
   * Default flag (if set to 'D', it is the default descriptor else blank)
   */
  @Property
  @PropertyLayout(
      sequence = "5",
      describedAs = "Default flag (if set to 'D', it is the default descriptor else blank)"
  )
  @Column(
      name = "RDEFAULT",
      allowsNull = "true",
      length = 2
  )
  @Getter
  @Setter
  private String defaultFlag;

  /**
   * Not in name flag (if set to 'N', the descriptor is not in the name else blank)
   */
  @Property
  @PropertyLayout(
      sequence = "6",
      describedAs = "Not in name flag (if set to 'N', the descriptor is not in the name else blank)"
  )
  @Column(
      name = "RNOTINNAME",
      allowsNull = "true",
      length = 2
  )
  @Getter
  @Setter
  private String notInNameFlag;

  /**
   * Order to displayed the facets within a group/subgroup
   */
  @Property
  @PropertyLayout(
      sequence = "7",
      describedAs = "Order to displayed the facets within a group/subgroup"
  )
  @Column(
      name = "ORDER_FAC",
      allowsNull = "true"
  )
  @Getter
  @Setter
  private Integer orderToDisplayedTheFacetsWithinAGroupOrSubgroup;

  /**
   * Order to displayed the descriptors within a group/subgroup and a facet
   */
  @Property
  @PropertyLayout(
      sequence = "8",
      describedAs = "Order to displayed the descriptors within a group/subgroup and a facet"
  )
  @Column(
      name = "ORDER_DESC",
      allowsNull = "true"
  )
  @Getter
  @Setter
  private Integer orderToDisplayedTheDescriptorsWithinAGroupOrSubgroupAndAFacet;
}
