/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Auto-generated by DitA-Tooling
package dita.globodiet.dom.params.food_table;

import jakarta.inject.Named;
import java.lang.String;
import javax.jdo.annotations.Column;
import javax.jdo.annotations.DatastoreIdentity;
import javax.jdo.annotations.PersistenceCapable;
import lombok.Getter;
import lombok.Setter;
import org.apache.causeway.applib.annotation.DomainObject;
import org.apache.causeway.applib.annotation.DomainObjectLayout;
import org.apache.causeway.applib.annotation.ObjectSupport;
import org.apache.causeway.applib.annotation.Property;
import org.apache.causeway.applib.annotation.PropertyLayout;
import org.apache.causeway.applib.annotation.Where;

/**
 * Nutrient values per nutrient and item
 */
@Named("dita.globodiet.params.food_table.NutrientValuesPerNutrientAndItem")
@DomainObject
@DomainObjectLayout(
        describedAs = "Nutrient values per nutrient and item"
)
@PersistenceCapable(
        table = "NTR_VALUE"
)
@DatastoreIdentity(
        strategy = javax.jdo.annotations.IdGeneratorStrategy.IDENTITY,
        column = "id"
)
public class NutrientValuesPerNutrientAndItem {
    /**
     * Item Sequential number
     */
    @Property
    @PropertyLayout(
            sequence = "1",
            describedAs = "Item Sequential number\n"
                            + "----\n"
                            + "required=true, unique=false",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "SEQ",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private int itemSequentialNumber;

    /**
     * Nutrient code
     */
    @Property
    @PropertyLayout(
            sequence = "2",
            describedAs = "Nutrient code\n"
                            + "----\n"
                            + "required=true, unique=false",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "NTR_CODE",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private int nutrientCode;

    /**
     * Nutrient value for the attached item & nutrient
     */
    @Property
    @PropertyLayout(
            sequence = "3",
            describedAs = "Nutrient value for the attached item & nutrient\n"
                            + "----\n"
                            + "required=true, unique=false",
            hidden = Where.NOWHERE
    )
    @Column(
            name = "VAL",
            allowsNull = "false"
    )
    @Getter
    @Setter
    private double nutrientValueForTheAttachedItemAndNutrient;

    @ObjectSupport
    public String title() {
        return this.toString();
    }
}
