/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *       http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Auto-generated by Causeway-Stuff code generator.
package dita.globodiet.cleaner;

import dita.globodiet.cleaner.dom.ConsumptionDataCleaner;
import dita.globodiet.cleaner.dom.ConsumptionDataCleanerDeps;
import dita.globodiet.cleaner.dom.ConsumptionDataCleaner_delete;
import dita.globodiet.cleaner.dom.ConsumptionDataCleaner_recipe;
import dita.globodiet.cleaner.dom.ConsumptionDataCleaner_survey;
import dita.globodiet.cleaner.dom.ConsumptionDataDefect;
import dita.globodiet.cleaner.dom.ConsumptionDataDefectDeps;
import dita.globodiet.cleaner.dom.ConsumptionDataDefect_delete;
import dita.globodiet.cleaner.dom.ConsumptionDataDefect_recipe;
import dita.globodiet.cleaner.dom.ConsumptionDataDefect_survey;
import java.lang.Class;
import java.lang.String;
import javax.annotation.processing.Generated;
import org.apache.causeway.commons.collections.Can;
import org.apache.causeway.commons.io.DataSource;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

@Generated("io.github.causewaystuff.companion.codegen.domgen._GenModule")
@Configuration
@Import({

// Config Beans
ModuleConfig.class,

// Menu Entries
EntitiesMenu.class,

// Entities
ConsumptionDataCleaner.class,
ConsumptionDataDefect.class,

// Submodules
ConsumptionDataCleanerDeps.class,
ConsumptionDataDefectDeps.class,

// Mixins
ConsumptionDataCleaner_delete.class,
ConsumptionDataCleaner_recipe.class,
ConsumptionDataCleaner_survey.class,
ConsumptionDataDefect_delete.class,
ConsumptionDataDefect_recipe.class,
ConsumptionDataDefect_survey.class,
})
@EntityScan
public class DitaModuleGdCleaner {
    public static final String NAMESPACE = "dita.globodiet.cleaner";

    public static DataSource schemaSource() {
        return DataSource.ofResource(dita.globodiet.cleaner.DitaModuleGdCleaner.class, "companion-schema.yaml");
    }

    public static Can<Class<?>> entityClasses() {
        return Can.of(ConsumptionDataCleaner.class,
        ConsumptionDataDefect.class);
    }
}
